export const APP_STRINGS = {
  inventory: {
    title: 'INVENTORY',
    emptyTitle: 'NO PRODUCTS',
    emptySubtitle: 'Tap + to add your first item.',
    noResultsTitle: 'NO RESULTS',
    noResultsSubtitle: 'Try a different search term.',
    errorConnection: 'Check your connection and try again.',
  },
  header: {
    searchPlaceholder: 'Search products...',
    searchAccessibility: 'Search products',
    clearSearch: 'Clear search',
    openSearch: 'Open search',
    addNewItem: 'Add new item',
  },
  createItem: {
    title: 'ADD PRODUCT',
    submitLabel: 'Add Product',
    errorTitle: 'Error',
    errorDefaultMessage: 'Failed to create item.',
  },
  itemDetail: {
    screenTitle: 'PRODUCT',
    deleteAlertTitle: 'Delete Item',
    deleteAlertMessage: 'This action cannot be undone.',
    deleteAlertCancel: 'Cancel',
    deleteAlertConfirm: 'Delete',
    deleteErrorDefault: 'Failed to delete item.',
    loadErrorMessage: 'Failed to load this item.',
    errorTitle: 'Error',
    noDescription: 'No description provided.',
    quantityLabel: 'QUANTITY',
    priceLabel: 'UNIT PRICE',
    descriptionLabel: 'DESCRIPTION',
    readMore: 'Read More',
    readLess: 'Read Less',
    editButton: 'EDIT ITEM',
    deleteButton: 'DELETE',
    editAccessibility: 'Edit item',
    deleteAccessibility: 'Delete item',
    readMoreAccessibility: 'Read more description',
    readLessAccessibility: 'Read less description',
  },
};
